---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Route53 DNS records for Stornoway website'

Parameters:
  DomainName:
    Type: String
    Description: 'The domain name and the S3 bucket name at the same time'
  CloudFrontDistributionDomainName:
    Type: String
    Description: 'The domain name of the CloudFront distribution to which the DNS records will point'
  
  # With default values
  HostedZoneId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: 'The ID of the Route53 hosted zone'
    Default: '/hosted-zone/molnarbence.dev/id'
  CloudFrontHostedZoneId:
    Type: String
    Description: "AWS's fixed hosted zone ID for CloudFront distributions, required by Route53 alias records that target a CloudFront distribution. This is a constant defined by AWS (same for every account), not a zone you own or manage."
    Default: 'Z2FDTNDATAQYW2'

Resources:
  AliasRecord:
    UpdateReplacePolicy: 'Delete'
    Type: 'AWS::Route53::RecordSet'
    DeletionPolicy: 'Delete'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub '${DomainName}.'
      Type: 'A'
      AliasTarget:
        DNSName: !Ref CloudFrontDistributionDomainName
        HostedZoneId: !Ref CloudFrontHostedZoneId
